default['virtuoso']['install_dir'] = '/usr/local/virtuoso'
default['virtuoso']['code_user']='root'
default['virtuoso']['code_group']='root'
default['virtuoso']['code_dir']='/usr/local/src/virtuoso'
default['virtuoso']['revision']='stable/7'
default['virtuoso']['cflags']='-O2 -m64'
